### ISSUE TITLE
hard to read text in spelling suggestions pop-over

### ISSUE THREAD

**Issue by bmesuere** [silvestreh/atom-material-syntax-light#1]
In the pop-over containing the spelling suggestions, the selected item is hard to read. A lighter (white) font-color is probably better here.
![screenshot](https://cloud.githubusercontent.com/assets/481872/9659602/a77581a4-5251-11e5-86e7-7177fde3763c.png)

**Comment by silvestreh** [comment]
True! But I believe this belongs to the UI theme. If you've got a minute, report it in the UI theme's repo. Thanks!
